# Generated by Django 4.2.7 on 2023-12-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_usernumbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNumbers',
            new_name='UserNumber',
        ),
    ]
